version: '3'

services:
  

  frontend:
    image: Front/front:2.0
    ports:
      - "4200:4200"

  backend:
    image: Back/back:2.2
    ports:
      - "3000:3000"
    depends_on:
       database:
          condition: service_started
       
  database:
    image: postgres
    environment:
      POSTGRES_DB: sistemaPracticaCapstone
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: disc2022  
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data: 
