---
services:
  sigelbackend:
    image: sigel/backend:1.0
    container_name: sigelbackend
    expose:
      - "80:3000"
    depends_on:
      - sigeldatabase

  sigeldatabase:
    image: postgres:16.2-alpine3.19
    container_name: sigeldatabase
    environment:
      - POSTGRES_DB=sigel
      - POSTGRES_USER=sigel
      - POSTGRES_PASSWORD=mane_bled_scraped_purged
    volumes:
      - ./data:/var/lib/postgresql/data

  sigelfrontend:
    image: sigel/frontend:1.0
    container_name: sigelfrontend
    expose:
      - "80:4200"
    depends_on:
      - sigelbackend
