version: '3'

services:
  backend:
    image: Back/back:1.0
    ports:
      - "3000:3000"
    depends_on:
      - database

  database:
    image: postgres
    environment:
      POSTGRES_DB: sistemaPracticaCapstone
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: disc2022
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:

